version: '3.8'

services:
  web:
    build: .
    container_name: employee_file_sender
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./instance:/app/instance  # SQLite database persistence
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    env_file:
      - .env
    command: flask run --host=0.0.0.0
    restart: unless-stopped
